# Lidar2OSM Processing Configuration

main_bag_directory_path: "/root/data"
main_output_directory_path:  "/root/data"
generate_sequence_run_stats: false
display_rosbag_data: false

sequences:
  kittredge_loop: 
    sequence_bag_path: "kittredge_loop/rosbags/liosam"
    binarized_sub_dir: "kittredge_loop/binarized/{robot_name}"
    robots: [1]

  # main_campus: 
  #   robots: [1]